name: Newman using trello

# Controls when the workflow will run
on:
 
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

     
      - name: install htmlextra
        run:  npm install -g newman-reporter-htmlextra

      # Runs a single command using the runners shell
      - name: Run newman
        run: newman run 'newman.postman_collection.json' -r "cli,json,junit,htmlextra" --global-var "KEY=${{env.KEY}}"  --global-var "TOKEN=${{env.TOKEN}}"  --global-var "BOARDID=${{env.BOARDID}}"   --global-var "BOARDNAME=${{env.BOARDNAME}}"   --global-var "LISTID=${{env.LISTID}}" --global-var "CARDID=${{env.CARDID}}"
 
      - uses: actions/upload-artifact@v4
        with:
           name: newman-reports
           path: ./newman
   
